### ISSUE TITLE
bug: DownloadError removed in 1.8.x (not restored by #121), docs still reference it; get_parser() raises bare RuntimeError

### ISSUE THREAD

**Issue by amondnet** [kreuzberg-dev/tree-sitter-language-pack#133]
### Description

`DownloadError` was a public exception in the Python binding (raised by the auto-download path and used as a type in `except` clauses), but it no longer exists in 1.8.1. It is not exported from `tree_sitter_language_pack` (not in `__all__`), not present in `tree_sitter_language_pack.exceptions`, and the string does not appear anywhere in the installed package.

This looks like a sibling of #121: the 1.8.0 redesign dropped several public Python symbols. #121 restored `SupportedLanguage` and `Parser`/`Language` pass-through in 1.8.1 (commit b88a907bc), but `DownloadError` was **not** restored.

Tracing it back, `DownloadError` was removed in **8557c1509** (`feat: migrate to alef polyglot binding generator (WIP)`), which replaced the hand-written exceptions with an auto-generated taxonomy (`DynamicLoadError`, `IoError`, `ParserSetupError`, …). The immediately preceding change to the same file, **4473da977** (#94, "fix Python error types"), had actually *added* `DownloadError` routing — so the symbol went from 10 occurrences in `crates/ts-pack-python/src/lib.rs` to 0 across that single commit.

Two concrete problems for downstream code:

1. **`DownloadError` is gone, with no replacement and no migration note.** Code that did `from tree_sitter_language_pack import DownloadError` (a documented public symbol) breaks with `ImportError` on import.
2. **Download/lookup failures from `get_parser()` now raise a bare `builtins.RuntimeError`** instead of a typed exception. The message is `Download error: Language '...' not available for download`, but the type is `RuntimeError`, so `except LanguageNotFoundError` / `except DownloadError` no longer catches it.

Additionally, the docs still advertise `DownloadError` as a public exception, so the docs and the shipped package disagree:
- `skills/tree-sitter-language-pack/references/python-api.md` — `` - `DownloadError`: Download or cache operation failed``
- `CHANGELOG.md` — references `DownloadError: ... io: invalid peer certificate` in the #125 entry

### Steps to reproduce

With `tree-sitter-language-pack==1.8.1`:

```python
# Worked on 1.6.x, raises ImportError on 1.8.1:
from tree_sitter_language_pack import DownloadError
# ImportError: cannot import name 'DownloadError' from 'tree_sitter_language_pack'
```

```python
import tree_sitter_language_pack as p
print(p.__version__)                       # 1.8.1
print("DownloadError" in p.__all__)        # False

import tree_sitter_language_pack.exceptions as exc
print(sorted(n for n in dir(exc) if n.endswith("Error") or n == "Error"))
# ['ConfigError', 'DynamicLoadError', 'Error', 'InvalidRangeError', 'IoError',
#  'LanguageNotFoundError', 'LockPoisonedError', 'NullLanguagePointerError',
#  'ParseFailedError', 'ParserSetupError', 'QueryError']

from tree_sitter_language_pack import get_parser
try:
    get_parser("not_a_real_language")
except Exception as e:
    print(type(e).__module__ + "." + type(e).__name__, "::", e)
# builtins.RuntimeError :: Download error: Language 'not_a_real_language' not available for download...
```

### Relevant files and configuration

- Removal: 8557c1509 (`crates/ts-pack-python/src/lib.rs`, `DownloadError` 10 → 0)
- Prior add: 4473da977 (#94)
- #121 fix that restored other symbols but not this one: b88a907bc
- Stale docs: `skills/tree-sitter-language-pack/references/python-api.md`, `CHANGELOG.md`

Either restoring `DownloadError` (raised from `get_parser`/download paths) or, at minimum, documenting the new exception types and removing `DownloadError` from the docs would resolve the docs/runtime mismatch.

**Comment by Goldziher** [comment]
Fixed in [`660ce0f9`](https://github.com/kreuzberg-dev/tree-sitter-language-pack/commit/660ce0f9) on `main`.

Root cause: the `Download`, `ChecksumMismatch`, and `CacheLock` variants on the core `Error` enum (`crates/ts-pack-core/src/error.rs`) were `#[cfg(feature = "download")]`-gated, and alef's variant extractor skipped cfg-gated variants when generating the public exception taxonomy. The three variants are pure string carriers with no extra dependencies, so the cfg gates were unnecessary — they now live unconditionally on the enum. (`Json` and `Toml` remain feature-gated because they carry external dependency types.)

The next regen extracts these as `DownloadError`, `ChecksumMismatchError`, and `CacheLockError` in `tree_sitter_language_pack.exceptions` (and equivalents in every other binding), restoring the documented `except DownloadError` catch path. `get_parser("not_a_real_language")` will raise the typed `DownloadError` instead of a bare `RuntimeError`.

Will ship in **v1.9.0**.
