### ISSUE TITLE
bug: 1.8.0 breaks public API (SupportedLanguage removed, Parser.parse() gone)

### ISSUE THREAD

**Issue by Pringled** [kreuzberg-dev/tree-sitter-language-pack#121]
### Description

tree-sitter-language-pack 1.8.0 removes two previously public API symbols without a deprecation notice or migration guide:                                                                
                                              
1. SupportedLanguage: a str type alias that was importable and used as a type annotation which no longer exists in __init__.py.                                                              
2. get_parser(): still importable, but now returns a Parser object with no methods at all, breaking any code that calls .parse() on it.

### Steps to reproduce

This works on 1.6.2, raises ImportError on 1.8.0:                  
```python                                                                                           
from tree_sitter_language_pack import SupportedLanguage
```

This works on 1.6.2, raises AttributeError on 1.8.0:
```python                                       
parser = get_parser("python")                                                                                                                                                             
tree = parser.parse(b"def foo(): pass")  # AttributeError: 'Parser' object has no attribute 'parse'
```

**Comment by Goldziher** [comment]
Fixed in [v1.8.1](https://github.com/kreuzberg-dev/tree-sitter-language-pack/releases/tag/v1.8.1).

- `from tree_sitter_language_pack import SupportedLanguage` works again (re-exported as `Literal[306]` of every grammar in the pack).
- `get_parser(...).parse(b"...")` returns a real `tree_sitter.Tree` again. `get_parser` / `get_language` now return native `tree_sitter.Parser` / `tree_sitter.Language` instances via PyO3 capsule pass-through (alef v0.15.39 wires `capsule_types` end-to-end through gen_bindings).

Smoke check:
```python
import tree_sitter
from tree_sitter_language_pack import SupportedLanguage, get_parser, get_language
p = get_parser('python')
assert isinstance(p, tree_sitter.Parser)
assert isinstance(get_language('python'), tree_sitter.Language)
assert p.parse(b'def f(): pass').root_node.type == 'module'
```
